apiVersion: v1
kind: ResourceQuota
metadata:
  name: backstage-quota
  namespace: backstage  # set by overlay namespace field
spec:
  hard:
    # Workload
    pods: "10"
    # Compute
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    # Storage
    requests.storage: 20Gi
    persistentvolumeclaims: "4"
    # Services
    services: "5"
    services.loadbalancers: "0"
    services.nodeports: "0"
    # Config
    configmaps: "20"
    secrets: "20"
